// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMYXcvHZoTNdAk8ogEiOlIq6PxiKt82A',
    appId: '1:130871168826:web:022eb6aea9edaf9fb64a03',
    messagingSenderId: '130871168826',
    projectId: 'linkup-a8a1c',
    authDomain: 'linkup-a8a1c.firebaseapp.com',
    storageBucket: 'linkup-a8a1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HbOfVwCQ2LNn6Hl5uYaSUl4V0OgD6ok',
    appId: '1:130871168826:android:58e8ce28e0bfadf3b64a03',
    messagingSenderId: '130871168826',
    projectId: 'linkup-a8a1c',
    storageBucket: 'linkup-a8a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnU4hbEaz-gAOL7rkK3HnsgAehc_--h3c',
    appId: '1:130871168826:ios:adbfeaec86b7676db64a03',
    messagingSenderId: '130871168826',
    projectId: 'linkup-a8a1c',
    storageBucket: 'linkup-a8a1c.appspot.com',
    iosClientId: '130871168826-cu5ut0t4ibqhamsuq2tpsscu6r4erqat.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnU4hbEaz-gAOL7rkK3HnsgAehc_--h3c',
    appId: '1:130871168826:ios:adbfeaec86b7676db64a03',
    messagingSenderId: '130871168826',
    projectId: 'linkup-a8a1c',
    storageBucket: 'linkup-a8a1c.appspot.com',
    iosClientId: '130871168826-cu5ut0t4ibqhamsuq2tpsscu6r4erqat.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeMYXcvHZoTNdAk8ogEiOlIq6PxiKt82A',
    appId: '1:130871168826:web:37d97649faf2e492b64a03',
    messagingSenderId: '130871168826',
    projectId: 'linkup-a8a1c',
    authDomain: 'linkup-a8a1c.firebaseapp.com',
    storageBucket: 'linkup-a8a1c.appspot.com',
  );
}
